### ISSUE TITLE
http.service.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [DKuznetsov1/ng-test#10]
При старте приложения запускается загрузка продуктов - метод 
// Promise approach
  get<T>(url: string): Promise<T> {
    return this.http.get(this.baseUrl + url)
      .toPromise()
      .then( response => <T>response)
      .catch(this.handlePromiseError);
  }

но this.baseUrl оказывается undefined.
Http failure response for http://localhost:4200/undefinedproducts: 404 Not Found

**Comment by DKuznetsov1** [comment]
Fixed

**Comment by DKuznetsov1** [comment]
Seems like not fixed....

**Comment by DKuznetsov1** [comment]
fixed in task6, task8
