### ISSUE TITLE
process-order.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [DKuznetsov1/ng-test#11]
Немного смутил этот код в теле конструктора
this.errorMessages = [];
    this.firstNameMinLength = 3;
    this.cityMinLength = 2;
    this.countryMinLength = 1;
    this.street1MinLength = 4;
    this.street2MinLength = 4;
Может быть можно сразу присвоить эти значения полям при их объявлении или перенести этот код в метод ngOnInit

**Comment by DKuznetsov1** [comment]
Done. Хотя я думал, что начальная инициализация как раз должна быть в конструкторе.
