### ISSUE TITLE
ngOnInit

### ISSUE THREAD

**Issue by VZhyrytskiy** [DKuznetsov1/ng-test#12]
Правильно ли я понимаю, если пользователь ничего не купил, то мы его заставим, купить ProductCategory.Drink? :)

ngOnInit() {
    this.order = this.orderService.currentOrder;
    if (!this.order) {
      console.log('WRONG!!!');
        this.order = new Order(
        1,
        [
          new OrderItem(
            new Product(1, '', 123, ProductCategory.Drink, true, []),
            2
          )
        ],
        new Date(),
        true
      );
    }

**Comment by DKuznetsov1** [comment]
Done.

Там стоит гард, и в тот if не попадет. Просто забыл убрать дебажный код.
