### ISSUE TITLE
app.component.html

### ISSUE THREAD

**Issue by VZhyrytskiy** [DKuznetsov1/ng-test#3]
<app-cart
  (buyEvent)="onBuy($event)"
  (cancelCartEvent)="onCancelCart($event)"></app-cart>
Думаю не стоит добавлять для событий суффикс Event. Есть соглашние (eventName)="onEventName(...)" Использование () и так говорит, что это ивент.

**Comment by DKuznetsov1** [comment]
Отчасти согласен. На самом деле постоянно хочется назвать эмитер и метод компонента одинаково, чтоб не путаться потом в подписках на ивент из других компонентов. Как то так:
```
add (task) {
  add.emit(task);
}
```

А так приходится писать аля
```
addTask (task) {
  add.emit(task);
}
```
Мне это не очень нравится, так как для меня addTask и add звучат практически одинаково. Тяжело только из названия понять, что из этого метод класса, а что эмитер событий.

**Comment by DKuznetsov1** [comment]
Исправил в Task5

**Comment by VZhyrytskiy** [comment]
Назвать одинаково не получиться, так как это свойство и метод класса. Они не могут одинаково называться.
