### ISSUE TITLE
border.directive.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [DKuznetsov1/ng-test#4]
Для чего тут используется ngAfterViewInit?

**Comment by DKuznetsov1** [comment]
Мне почему-то запомнилось, что ngAfterViewInit позволяет удостоверится, что вьюшка уже построена и ссылка на элемент точно будет установлена. Хотя, наверно, неправильно запомнил. Исправил на OnInit - сработало нормально.

**Comment by VZhyrytskiy** [comment]
Обычно используется для манипуляции темплейтом. Например доступам к #var.
