### ISSUE TITLE
cart-sort.pipe.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [DKuznetsov1/ng-test#7]
Пайп достоточно сложный получился. Хотелось бы какие-то комментарии, а то вчитываться в алгоритмы - большая потеря времени.
for (let i = 0, n = a.length; i < n; ++i) {
        const k = a[i];
          if (k in o) {
              o = o[k];
          } else {
              return;
          }
      }

**Comment by DKuznetsov1** [comment]
Fixed in Task5
