### ISSUE TITLE
app.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [DKuznetsov1/ng-test#9]
async ngOnInit() {
    // console.log('AppComponent init');
    await this.httpService.init();
    const user = this.userService.createAnonymousUser();
    this.userService.setUser(user);
  }
Мое субъективное мнение. Я бы не делал асинхронными методы жизненного цикла и по возможности публичные методы. Создал бы приватный метод и его сделал бы асинхронным. Это просто ощущение того, что в будуем может что-то сломаться или работаь не так, как сейчас. Приватность есть приватность. Поменять всегда проще.

**Comment by DKuznetsov1** [comment]
`await this.httpService.init();`
Это воркэраунд к другой проблеме. На самом деле HttpService использует AppSettingsService, который нужен ему для того, что бы взять вытянуть конфиг. А AppSettingsService первоначально использовал HttpService, потому как ему надо было вытянуть конфиг из файла. Как я понял это делается через хттп кол (поправьте если не так):
`this.httpService.get('assets/app-settings.json')`
Кросзависимость такая получилась. Убрал её использованием HttpClient вместо HttpService в AppSettingsService. Но тем не менее, из-за асинхронного кола за app-settings.json появляется необходимость в асинхронной инициализации HttpService 
`async init() { ...`

Подскажите, как мне стоит этот сервис проинициализировать асинхронно, если не использовать асинхронных методов жизненного цикла и асинхронных публичных методов?

**Comment by VZhyrytskiy** [comment]
Ничего плохого в том, что вы используете асинхронные функции нет. Это удобно. В задании ваши httpService и AppSettingsService - это абсолютно два разных сервиса. (Пункт 2 и пункт 5). Вы решили их объединить и увеличили сложность. Может не нужно так делать?

**Comment by DKuznetsov1** [comment]
Исправил в Таск8.
Но вообще вопрос актуален
Надо проинициализировать сервис асинхронно один раз на старте приложения. 
Сейчас получалось так (https://github.com/DKuznetsov1/ng-test/tree/46dd1283e8fda20dcaa0d0eec6935688ad31df32):
1. Начинает инициализироваться AppComponent
2. Запускает инициализацию httpService ( await httpService.init() ), который в свою очередь начинает асинронно брать для себя конфиг.
3. AppComponent init не смотря на наличие await не дожидается респонса от HttpClient.get('assets/app-settings.json').toPromise()
4. Начинает инициализироваться ProductListComponent
5. Запрос 'undefined/products'  дает ошибку, потому что HttpClient.get('assets/app-settings.json').toPromise() до сих пор не завершился
6. Приходит ответ от HttpClient.get('assets/app-settings.json').toPromise(), но уже поздно

Что посоветуете?

**Comment by VZhyrytskiy** [comment]
Если надо выполнить цепочку асинхроных действий, то можно воспользоваться promise.then().then().then()...
Если надо выполнить дейсвтие после завершения нескольких асинхронных действий, то Promise.all([promise1, promise2,]).then()

**Comment by DKuznetsov1** [comment]
Это понятно. Но как заставить, что бы все остальные ngOnit запускались только после резолва промиса текущего компонента? 
То что я хочу сделать ниже:
1. Запустить инициализацию сервиса в ngOnit AppComponent
2. Все остальные компоненты по цепочке инициализировать только после того, как зарезолвится промис асинхронной инициализации сервиса (сейчас этого не происходит видимо)
Или это не реализуемо сейчас? потому что выглядит что ngOnit'ы ангуляром не евейтаются...

**Comment by VZhyrytskiy** [comment]
await не останавливает дальнейший код. Он позволяет выйти из функции и затем заново вернуться в нее. Это не значит, что другие компоненты не будут инициализироваться. Будут, а ждать не будут.

**Comment by DKuznetsov1** [comment]
Ну почему же. Я просто не знаю как компоненты инициализируются. Если бы они инициализровались по схеме:
ngOnit1().then(ngOnInit2).then(ngOnInit3) то они бы ждали друга друга. 
Правильно ли я понимаю, что то что я хочу сделать сейчас нереализуемо?

**Comment by VZhyrytskiy** [comment]
Думаю, что такое, наверное, нельзя реализовать. Может быть стоит подумать в сторону того, чтобы все-таки проинициализировать компоненты, но когда зарезолвиться промис в рутовом компоненте, то передать в другие компоненты какие-то параметры. Слушать их изменение и выполнять дальнейшие шаги. Можно также построить для передачи данных какой-то сервис на основе Observable. Пока не знаю, можно ли как-то остановить выполнение ngOnInit других компонентов.

**Comment by DKuznetsov1** [comment]
Угу понял, спасибо.
